"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ht" | "en" | "es";

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  ht: {
    admin: "Admin",
    adminDashboard: "Tablo admin",
    adminLogin: "Koneksyon admin",
    adminReviewBody: "Admin yo ka apwouve, refize, epi swiv istwa prè yo.",
    adminReviewTitle: "Revizyon admin",
    allStatuses: "Tout",
    adminAccessDenied: "Kont sa a pa gen aksè admin.",
    approve: "Apwouve",
    back: "Retounen",
    basicInfo: "Enfo debaz",
    checkStatus: "Tcheke estati",
    checking: "Ap tcheke...",
    capturePhoto: "Pran foto",
    cameraAccessError: "Nou pa kapab ouvri kamera a. Tanpri verifye pèmisyon kamera a oswa telechaje yon foto.",
    cameraPreview: "Apèsi kamera",
    cancelRequest: "Anile demann",
    cancelRequestSuccess: "Demann lan anile.",
    closeCamera: "Fèmen kamera",
    continue: "Kontinye",
    countryHaiti: "Ayiti",
    countryMexico: "Meksik",
    countryUsa: "Etazini",
    createAccount: "Kreye kont",
    currency: "Lajan",
    dashboard: "Tablo mwen",
    dayUnit: "jou",
    destinationCountry: "Nan ki peyi ou bezwen lajan an?",
    destinationFallback: "Destinasyon",
    dueDate: "Dat limit",
    dueIn: "Pou peye nan",
    email: "Imel",
    filterByStatus: "Filtre pa estati",
    fullName: "Non konplè",
    haitiMobileNumber: "Nimewo MonCash/NatCash",
    haitiAccountName: "Non sou kont lan",
    haitiPhoneHelp: "MonCash dwe se Digicel. NatCash dwe se Natcom.",
    haitiPhoneLengthError: "Mete yon nimewo Ayiti 8 chif, ak +509 oswa san +509.",
    openCamera: "Ouvri kamera",
    heroBody:
      "On platfòm kredi ki fet pou kominote ayisyen an prete lajan, verifye istwa kredi, epi swiv desizyon ak yon nimewo referans klè.",
    idPhoto: "Foto pyès idantite",
    identityChecksBody: "Telechaje pyès idantite, selfie, ak selfie ak pyès idantite nan Supabase Storage.",
    identityChecksTitle: "Verifikasyon idantite",
    interest: "Enterè",
    language: "Lang",
    loadingAdminData: "Done admin yo ap chaje...",
    loadingLoanHistory: "Istwa prè yo ap chaje...",
    loadingTracker: "Zouti swivi a ap chaje...",
    loanAmount: "Kantite lajan",
    loanHistoryBody: "Gade istwa demann ou yo ak estati ranbousman yo.",
    loanInfo: "Enfo prè",
    login: "Konekte",
    menu: "Meni",
    markPaid: "Make kòm peye",
    methodBankTransfer: "Transfè labank",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Non sou kont lan",
    mexicoBankName: "Non bank lan",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash mande yon nimewo Digicel.",
    myLoans: "Prè mwen yo",
    natcashNatcomError: "NatCash mande yon nimewo Natcom.",
    noReceivingDetails: "Pa gen enfòmasyon pou resevwa lajan",
    notProvided: "Pa bay",
    password: "Modpas",
    payoutInfo: "Enfo pou resevwa lajan",
    payoutMethod: "Kijan ou vle resevwa lajan an?",
    phoneNumber: "Nimewo telefòn",
    referenceNumber: "Nimewo referans",
    reject: "Refize",
    repaymentPeriod: "Peryòd ranbousman",
    repayment: "Ranbousman",
    requested: "Kantite mande",
    rate: "to",
    receiverLabel: "Moun k ap resevwa",
    reviewRequestsBody: "Revize demann yo, tcheke dokiman yo, epi jere estati ranbousman yo.",
    requestLoan: "Mande prè",
    requestSummary: "Rezime demann lan",
    requestStatusTitle: "Swiv yon demann",
    selfie: "Selfie",
    selfieWithId: "Selfie ak pyès idantite",
    selectedFile: "Fichye chwazi",
    simpleRequestsBody: "Voye enfòmasyon kontak, kantite lajan, ak apèsi ranbousman an.",
    simpleRequestsTitle: "Demann senp",
    signOut: "Dekonekte",
    statusApproved: "Apwouve",
    statusCanceled: "Anile",
    statusPaid: "Peye",
    statusPending: "Ann atant",
    statusRejected: "Refize",
    submitLoanError: "Nou pa kapab voye demann prè a.",
    submitRequest: "Voye demann",
    submitting: "Ap voye...",
    supabaseMissing: "Supabase poko konfigire. Ajoute NEXT_PUBLIC_SUPABASE_URL ak NEXT_PUBLIC_SUPABASE_ANON_KEY nan .env.local, epi rekòmanse sèvè a.",
    noLoansFound: "Pa gen prè",
    noLoansFoundBody: "Lè ou mande yon prè, li ap parèt isit la.",
    noRequestFound: "Nou pa jwenn okenn demann ak nimewo referans sa a.",
    newRequest: "Nouvo demann",
    totalPayback: "Total pou peye",
    track: "Swiv",
    useLoginFirst: "Ou dwe konekte anvan.",
    usaReceiver: "Imel, telefòn, oswa $Cashtag",
    identityVerification: "Verifikasyon idantite",
    rejectIdentityAction: "Refize idantite",
    submitVerification: "Voye verifikasyon",
    verificationIntro: "Pran oswa telechaje pyès idantite, selfie, ak selfie ak pyès idantite. PRETEM ap itilize sa pou revize kont ou yon sèl fwa.",
    verificationNot_submitted: "Pa voye",
    verificationNotSubmitted: "Pa voye",
    verificationPending: "Ann atant",
    verificationPendingBody: "Verifikasyon ou an ann atant. Ou ka mande prè pandan admin nan ap revize dokiman yo.",
    verificationRejected: "Refize",
    verificationRejectedBody: "Verifikasyon an pa pase. Tanpri voye foto yo ankò ak enfòmasyon ki klè.",
    verificationStatus: "Estati verifikasyon",
    verificationSubmitError: "Nou pa kapab voye verifikasyon an.",
    verificationSubmitted: "Verifikasyon an voye. Admin nan ap revize li.",
    verificationVerified: "Verifye",
    verificationVerifiedBody: "Idantite ou verifye. Ou ka kontinye mande prè.",
    verifyBeforeLoan: "Tanpri verifye idantite ou anvan ou mande prè.",
    verifyIdentity: "Verifye idantite",
    verifyIdentityAction: "Verifye idantite",
    verification: "Verifikasyon"
  },
  en: {
    admin: "Admin",
    adminDashboard: "Admin dashboard",
    adminLogin: "Admin login",
    adminReviewBody: "Admins can approve, reject, and track loan history.",
    adminReviewTitle: "Admin review",
    allStatuses: "All",
    adminAccessDenied: "This account does not have admin access.",
    approve: "Approve",
    back: "Back",
    basicInfo: "Basic info",
    checkStatus: "Check status",
    checking: "Checking...",
    capturePhoto: "Take photo",
    cameraAccessError: "Could not open the camera. Please check camera permissions or upload a photo.",
    cameraPreview: "Camera preview",
    cancelRequest: "Cancel request",
    cancelRequestSuccess: "Request canceled.",
    closeCamera: "Close camera",
    continue: "Continue",
    countryHaiti: "Haiti",
    countryMexico: "Mexico",
    countryUsa: "USA",
    createAccount: "Create account",
    currency: "Currency",
    dashboard: "Dashboard",
    dayUnit: "days",
    destinationCountry: "Which country do you need the money in?",
    destinationFallback: "Destination",
    dueDate: "Due date",
    dueIn: "Due in",
    email: "Email",
    filterByStatus: "Filter by status",
    fullName: "Full name",
    haitiMobileNumber: "MonCash/NatCash phone number",
    haitiAccountName: "Name on account",
    haitiPhoneHelp: "MonCash must be a Digicel number. NatCash must be a Natcom number.",
    haitiPhoneLengthError: "Use an 8-digit Haiti phone number, with or without +509.",
    openCamera: "Open camera",
    heroBody:
      "A practical micro-loan platform built for the Haitian community to request funds, complete identity verification, and track decisions with a clear reference number.",
    idPhoto: "ID photo",
    identityChecksBody: "Upload ID, selfie, and selfie with ID into Supabase Storage.",
    identityChecksTitle: "Identity checks",
    interest: "Interest",
    language: "Language",
    loadingAdminData: "Loading admin data...",
    loadingLoanHistory: "Loading loan history...",
    loadingTracker: "Loading tracker...",
    loanAmount: "Loan amount",
    loanHistoryBody: "View your request history and repayment status.",
    loanInfo: "Loan info",
    login: "Log in",
    menu: "Menu",
    markPaid: "Mark paid",
    methodBankTransfer: "Bank transfer",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Account name",
    mexicoBankName: "Bank name",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash requires a Digicel number.",
    myLoans: "My loans",
    natcashNatcomError: "NatCash requires a Natcom number.",
    noReceivingDetails: "No receiving details",
    notProvided: "Not provided",
    password: "Password",
    payoutInfo: "Receiving information",
    payoutMethod: "How do you want to receive the money?",
    phoneNumber: "Phone number",
    referenceNumber: "Reference number",
    reject: "Reject",
    repaymentPeriod: "Repayment period",
    repayment: "Repayment",
    requested: "Requested",
    rate: "rate",
    receiverLabel: "Receiver",
    reviewRequestsBody: "Review requests, inspect verification uploads, and manage repayment state.",
    requestLoan: "Request loan",
    requestSummary: "Request summary",
    requestStatusTitle: "Track a request",
    selfie: "Selfie",
    selfieWithId: "Selfie with ID",
    selectedFile: "Selected file",
    simpleRequestsBody: "Submit basic contact details, amount, and repayment preview.",
    simpleRequestsTitle: "Simple requests",
    signOut: "Sign out",
    statusApproved: "Approved",
    statusCanceled: "Canceled",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusRejected: "Rejected",
    submitLoanError: "Could not submit loan request.",
    submitRequest: "Submit request",
    submitting: "Submitting...",
    supabaseMissing: "Supabase is not configured yet. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to .env.local, then restart the dev server.",
    noLoansFound: "No loans found",
    noLoansFoundBody: "Once you request a loan, it will appear here.",
    noRequestFound: "No loan request was found for that reference.",
    newRequest: "New request",
    totalPayback: "Total payback",
    track: "Track",
    useLoginFirst: "You must be logged in.",
    usaReceiver: "Email, phone, or $Cashtag",
    identityVerification: "Identity verification",
    rejectIdentityAction: "Reject identity",
    submitVerification: "Submit verification",
    verificationIntro: "Take or upload your ID, selfie, and selfie with ID. PRETEM will use this to review your account once.",
    verificationNot_submitted: "Not submitted",
    verificationNotSubmitted: "Not submitted",
    verificationPending: "Pending",
    verificationPendingBody: "Your verification is pending. You can request a loan while the admin reviews the documents.",
    verificationRejected: "Rejected",
    verificationRejectedBody: "The verification was not accepted. Please upload clear photos again.",
    verificationStatus: "Verification status",
    verificationSubmitError: "Could not submit verification.",
    verificationSubmitted: "Verification submitted. The admin will review it.",
    verificationVerified: "Verified",
    verificationVerifiedBody: "Your identity is verified. You can continue to request a loan.",
    verifyBeforeLoan: "Please verify your identity before requesting a loan.",
    verifyIdentity: "Verify identity",
    verifyIdentityAction: "Verify identity",
    verification: "Verification"
  },
  es: {
    admin: "Admin",
    adminDashboard: "Panel de admin",
    adminLogin: "Inicio de admin",
    adminReviewBody: "Los administradores pueden aprobar, rechazar y revisar el historial de préstamos.",
    adminReviewTitle: "Revisión admin",
    allStatuses: "Todos",
    adminAccessDenied: "Esta cuenta no tiene acceso de admin.",
    approve: "Aprobar",
    back: "Atrás",
    basicInfo: "Información básica",
    checkStatus: "Ver estado",
    checking: "Verificando...",
    capturePhoto: "Tomar foto",
    cameraAccessError: "No se pudo abrir la cámara. Revisa los permisos de cámara o sube una foto.",
    cameraPreview: "Vista de cámara",
    cancelRequest: "Cancelar solicitud",
    cancelRequestSuccess: "Solicitud cancelada.",
    closeCamera: "Cerrar cámara",
    continue: "Continuar",
    countryHaiti: "Haiti",
    countryMexico: "México",
    countryUsa: "EE. UU.",
    createAccount: "Crear cuenta",
    currency: "Moneda",
    dashboard: "Panel",
    dayUnit: "días",
    destinationCountry: "¿En qué país necesitas el dinero?",
    destinationFallback: "Destino",
    dueDate: "Fecha de pago",
    dueIn: "Vence en",
    email: "Correo",
    filterByStatus: "Filtrar por estado",
    fullName: "Nombre completo",
    haitiMobileNumber: "Número MonCash/NatCash",
    haitiAccountName: "Nombre de la cuenta",
    haitiPhoneHelp: "MonCash debe ser Digicel. NatCash debe ser Natcom.",
    haitiPhoneLengthError: "Usa un número de Haiti de 8 dígitos, con o sin +509.",
    openCamera: "Abrir cámara",
    heroBody:
      "Una plataforma práctica de micropréstamos para la comunidad haitiana que permite solicitar fondos, completar la verificación de identidad y seguir decisiones con un número de referencia claro.",
    idPhoto: "Foto de identificación",
    identityChecksBody: "Sube identificación, selfie y selfie con identificación a Supabase Storage.",
    identityChecksTitle: "Verificación de identidad",
    interest: "Interés",
    language: "Idioma",
    loadingAdminData: "Cargando datos de admin...",
    loadingLoanHistory: "Cargando historial de préstamos...",
    loadingTracker: "Cargando rastreador...",
    loanAmount: "Monto del préstamo",
    loanHistoryBody: "Consulta tu historial de solicitudes y estado de pago.",
    loanInfo: "Información del préstamo",
    login: "Iniciar sesión",
    menu: "Menú",
    markPaid: "Marcar pagado",
    methodBankTransfer: "Transferencia bancaria",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Nombre de la cuenta",
    mexicoBankName: "Nombre del banco",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash requiere un número Digicel.",
    myLoans: "Mis préstamos",
    natcashNatcomError: "NatCash requiere un número Natcom.",
    noReceivingDetails: "No hay información para recibir",
    notProvided: "No proporcionado",
    password: "Contraseña",
    payoutInfo: "Información para recibir",
    payoutMethod: "¿Cómo quieres recibir el dinero?",
    phoneNumber: "Teléfono",
    referenceNumber: "Número de referencia",
    reject: "Rechazar",
    repaymentPeriod: "Plazo de pago",
    repayment: "Pago",
    requested: "Solicitado",
    rate: "tasa",
    receiverLabel: "Receptor",
    reviewRequestsBody: "Revisa solicitudes, verifica documentos y administra el estado de pago.",
    requestLoan: "Solicitar préstamo",
    requestSummary: "Resumen de solicitud",
    requestStatusTitle: "Rastrear solicitud",
    selfie: "Selfie",
    selfieWithId: "Selfie con identificación",
    selectedFile: "Archivo seleccionado",
    simpleRequestsBody: "Envía datos de contacto, monto y vista previa del pago.",
    simpleRequestsTitle: "Solicitudes simples",
    signOut: "Cerrar sesión",
    statusApproved: "Aprobado",
    statusCanceled: "Cancelada",
    statusPaid: "Pagado",
    statusPending: "Pendiente",
    statusRejected: "Rechazado",
    submitLoanError: "No se pudo enviar la solicitud.",
    submitRequest: "Enviar solicitud",
    submitting: "Enviando...",
    supabaseMissing: "Supabase aún no está configurado. Agrega NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_ANON_KEY a .env.local, luego reinicia el servidor.",
    noLoansFound: "No hay préstamos",
    noLoansFoundBody: "Cuando solicites un préstamo, aparecerá aquí.",
    noRequestFound: "No se encontró una solicitud con esa referencia.",
    newRequest: "Nueva solicitud",
    totalPayback: "Total a pagar",
    track: "Rastrear",
    useLoginFirst: "Debes iniciar sesión.",
    usaReceiver: "Correo, teléfono o $Cashtag",
    identityVerification: "Verificación de identidad",
    rejectIdentityAction: "Rechazar identidad",
    submitVerification: "Enviar verificación",
    verificationIntro: "Toma o sube tu identificación, selfie y selfie con identificación. PRETEM usará esto para revisar tu cuenta una sola vez.",
    verificationNot_submitted: "No enviada",
    verificationNotSubmitted: "No enviada",
    verificationPending: "Pendiente",
    verificationPendingBody: "Tu verificación está pendiente. Puedes solicitar un préstamo mientras el admin revisa los documentos.",
    verificationRejected: "Rechazada",
    verificationRejectedBody: "La verificación no fue aceptada. Sube fotos claras otra vez.",
    verificationStatus: "Estado de verificación",
    verificationSubmitError: "No se pudo enviar la verificación.",
    verificationSubmitted: "Verificación enviada. El admin la revisará.",
    verificationVerified: "Verificada",
    verificationVerifiedBody: "Tu identidad está verificada. Puedes continuar y solicitar un préstamo.",
    verifyBeforeLoan: "Verifica tu identidad antes de solicitar un préstamo.",
    verifyIdentity: "Verificar identidad",
    verifyIdentityAction: "Verificar identidad",
    verification: "Verificación"
  }
};

const languageLabels: Record<Language, string> = {
  ht: "Kreyol",
  en: "English",
  es: "Español"
};

const LanguageContext = createContext<{
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}>({
  language: "ht",
  setLanguage: () => undefined,
  t: (key) => key
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ht");

  useEffect(() => {
    const saved = window.localStorage.getItem("pretem-language") as Language | null;
    if (saved && dictionaries[saved]) setLanguageState(saved);
  }, []);

  const value = useMemo(
    () => ({
      language,
      setLanguage: (nextLanguage: Language) => {
        setLanguageState(nextLanguage);
        window.localStorage.setItem("pretem-language", nextLanguage);
      },
      t: (key: string) => dictionaries[language][key] ?? key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageSelect() {
  const { language, setLanguage, t } = useLanguage();

  return (
    <label className="language-select">
      <span>{t("language")}</span>
      <select value={language} onChange={(event) => setLanguage(event.target.value as Language)}>
        {Object.entries(languageLabels).map(([value, label]) => (
          <option key={value} value={value}>
            {label}
          </option>
        ))}
      </select>
    </label>
  );
}
