"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ht" | "en" | "es";

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  ht: {
    admin: "Admin",
    adminDashboard: "Tablo admin",
    adminDashboardBody: "Chwazi yon seksyon pou revize dokiman, trete nouvo demann, oswa jere prè ki deja ap mache.",
    adminLogin: "Koneksyon admin",
    adminReviewBody: "Admin yo ka apwouve, refize, epi swiv istwa prè yo.",
    adminReviewTitle: "Revizyon admin",
    allStatuses: "Tout",
    adminAccessDenied: "Kont sa a pa gen aksè admin.",
    actions: "Aksyon",
    acceptCreditReporting: "Mwen konprann si mwen pa respekte kondisyon ranbousman yo, PRETEM ka voye dosye a nan koleksyon oswa bay biwo kredi/konsomatè yo sèlman jan lalwa pèmèt sa.",
    acceptLawfulRecovery: "Mwen konprann si mwen pa respekte kondisyon prè a, PRETEM ka itilize mwayen legal pou rekipere lajan an, tankou rapèl prive, koleksyon, aksyon legal, oswa rapò kredi jan lalwa pèmèt sa.",
    acceptLoanTerms: "Mwen dakò ak tèm yo, total pou peye a, dat limit la, ak responsablite pou bay bon enfòmasyon.",
    acceptDocuments: "Aksepte dokiman yo",
    agreementRequired: "Ou dwe aksepte tout kondisyon obligatwa yo anvan ou voye demann lan.",
    approve: "Apwouve",
    approveLoan: "Apwouve prè",
    approveLoanNeedsDocs: "Aksepte dokiman idantite yo anvan ou apwouve prè a.",
    approvedShort: "Apwouve",
    authDescription: "PRETEM Credit ede kominote ayisyen an mande kredi, verifye idantite, epi swiv desizyon yo ak yon nimewo referans klè.",
    back: "Retounen",
    basicInfo: "Enfo debaz",
    checkStatus: "Tcheke estati",
    checking: "Ap tcheke...",
    capturePhoto: "Pran foto",
    cameraAccessError: "Nou pa kapab ouvri kamera a. Tanpri verifye pèmisyon kamera a oswa telechaje yon foto.",
    cameraPreview: "Apèsi kamera",
    cancelRequest: "Anile demann",
    cancelRequestSuccess: "Demann lan anile.",
    closeCamera: "Fèmen kamera",
    continue: "Kontinye",
    contact: "Kontak",
    countryHaiti: "Ayiti",
    countryMexico: "Meksik",
    countryUsa: "Etazini",
    createAccount: "Kreye kont",
    creditHistory: "Istwa kredi",
    creditScore: "Nòt kredi",
    currency: "Lajan",
    dashboard: "Tablo mwen",
    dashboardVerificationApproved: "Bon nouvèl: verifikasyon idantite ou aksepte. Ou ka kontinye mande prè.",
    dashboardVerificationNotSubmitted: "Ou poko voye verifikasyon idantite ou. Voye dokiman yo pou PRETEM ka revize kont ou.",
    dashboardVerificationPending: "Verifikasyon idantite ou toujou ann atant. PRETEM ap revize dokiman yo.",
    dashboardVerificationRejected: "Verifikasyon idantite ou pa aksepte. Tanpri voye foto klè ankò.",
    dayUnit: "jou",
    destinationCountry: "Nan ki peyi ou bezwen lajan an?",
    destinationFallback: "Destinasyon",
    documentReview: "Revizyon dokiman",
    documents: "Dokiman",
    dueDate: "Dat limit",
    dueIn: "Pou peye nan",
    download: "Telechaje",
    downloadAgreement: "Telechaje akò a",
    email: "Imel",
    filterByStatus: "Filtre pa estati",
    footerTrust: "Platfòm ofisyèl PRETEM Credit pou demann prè, verifikasyon idantite, ak swivi estati.",
    fullName: "Non konplè",
    haitiMobileNumber: "Nimewo MonCash/NatCash",
    haitiAccountName: "Non sou kont lan",
    haitiPhoneHelp: "MonCash dwe se Digicel. NatCash dwe se Natcom.",
    haitiPhoneLengthError: "Mete yon nimewo Ayiti 8 chif, ak +509 oswa san +509.",
    hidePassword: "Kache modpas",
    openCamera: "Ouvri kamera",
    open: "Ouvri",
    heroBody:
      "On platfòm kredi ki fet pou kominote ayisyen an prete lajan, verifye istwa kredi, epi swiv desizyon ak yon nimewo referans klè.",
    idPhoto: "Foto pyès idantite",
    identityChecksBody: "Telechaje pyès idantite, selfie, ak selfie ak pyès idantite nan Supabase Storage.",
    identityChecksTitle: "Verifikasyon idantite",
    interest: "Enterè",
    language: "Lang",
    loadingAdminData: "Done admin yo ap chaje...",
    loadingLoanHistory: "Istwa prè yo ap chaje...",
    loadingTracker: "Zouti swivi a ap chaje...",
    lastLoan: "Dènye prè",
    loanAmount: "Kantite lajan",
    loanDecision: "Desizyon prè",
    loanHistoryBody: "Gade istwa demann ou yo ak estati ranbousman yo.",
    loanInfo: "Enfo prè",
    loanManagement: "Jesyon prè",
    loanRequests: "Demann prè",
    loanSummary: "Rezime prè",
    loansShort: "prè",
    login: "Konekte",
    loginTagline: "Prè fasil ak rapid san istwa kredi",
    menu: "Meni",
    markPaid: "Make kòm peye",
    methodBankTransfer: "Transfè labank",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Non sou kont lan",
    mexicoBankName: "Non bank lan",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash mande yon nimewo Digicel.",
    myLoans: "Prè mwen yo",
    natcashNatcomError: "NatCash mande yon nimewo Natcom.",
    noReceivingDetails: "Pa gen enfòmasyon pou resevwa lajan",
    moneySent: "Lajan voye",
    notProvided: "Pa bay",
    password: "Modpas",
    paidShort: "Peye",
    pendingShort: "Ann atant",
    payoutInfo: "Enfo pou resevwa lajan",
    payoutMethod: "Kijan ou vle resevwa lajan an?",
    phoneNumber: "Nimewo telefòn",
    privacyPolicy: "Politik konfidansyalite",
    printVerification: "Enprime verifikasyon",
    printWindowBlocked: "Navigatè a bloke fenèt enpresyon an. Tanpri pèmèt pop-up pou sit sa a.",
    publicStoryConsent: "Opsyonèl: PRETEM ka kontakte mwen pou mande pèmisyon apa pou pataje temwayaj oswa foto maketing ki pa sansib.",
    publicStoryConsentHelp: "PRETEM pap pibliye non, foto, pyès idantite, selfie ak ID, enfòmasyon dèt, oswa dokiman prive verifikasyon sou rezo sosyal.",
    referenceNumber: "Nimewo referans",
    reject: "Refize",
    rejectDocuments: "Refize dokiman yo",
    rejectLoan: "Refize prè",
    rejectedShort: "Refize",
    repaymentPeriod: "Peryòd ranbousman",
    repayment: "Ranbousman",
    repaymentProof: "Prèv ranbousman",
    repaymentSubmitted: "Prèv ranbousman an voye.",
    repaymentTransferId: "ID transfè ranbousman",
    requested: "Kantite mande",
    requiredAgreementHelp: "Ou dwe tcheke 3 kondisyon obligatwa yo pou voye demann lan.",
    rate: "to",
    receiverLabel: "Moun k ap resevwa",
    reviewRequestsBody: "Revize demann yo, tcheke dokiman yo, epi jere estati ranbousman yo.",
    requestLoan: "Mande prè",
    requestSummary: "Rezime demann lan",
    requestStatusTitle: "Swiv yon demann",
    selfie: "Selfie",
    selfieWithId: "Selfie ak pyès idantite",
    security: "Sekirite",
    securityConfidentialityPolicy: "Politik sekirite ak konfidansyalite",
    searchUsers: "Chèche moun",
    searchUsersPlaceholder: "Tape non, imel, telefòn, peyi, oswa referans",
    selectedFile: "Fichye chwazi",
    showPassword: "Montre modpas",
    simpleRequestsBody: "Voye enfòmasyon kontak, kantite lajan, ak apèsi ranbousman an.",
    simpleRequestsTitle: "Demann senp",
    signOut: "Dekonekte",
    sent: "Voye",
    signupCountry: "Peyi",
    statusApproved: "Apwouve",
    statusCanceled: "Anile",
    statusPaid: "Peye",
    statusPending: "Ann atant",
    statusRejected: "Refize",
    status: "Estati",
    submitLoanError: "Nou pa kapab voye demann prè a.",
    submitRequest: "Voye demann",
    submitting: "Ap voye...",
    submitRepayment: "Voye prèv peman",
    submitted: "Voye",
    termsDisclosure: "Tèm ak enfòmasyon prè",
    supabaseMissing: "Supabase poko konfigire. Ajoute NEXT_PUBLIC_SUPABASE_URL ak NEXT_PUBLIC_SUPABASE_ANON_KEY nan .env.local, epi rekòmanse sèvè a.",
    noLoansFound: "Pa gen prè",
    noAdminItems: "Pa gen anyen nan seksyon sa a pou kounye a.",
    noLoansFoundBody: "Lè ou mande yon prè, li ap parèt isit la.",
    noRequestFound: "Nou pa jwenn okenn demann ak nimewo referans sa a.",
    newRequest: "Nouvo demann",
    totalPayback: "Total pou peye",
    track: "Swiv",
    transferId: "ID transfè",
    transferIdRequired: "Mete ID transfè a anvan ou kontinye.",
    useLoginFirst: "Ou dwe konekte anvan.",
    users: "Itilizatè yo",
    usersDatabase: "Baz done itilizatè yo",
    usersDatabaseBody: "Tout moun ki itilize sistèm nan, ak enfòmasyon kont, nòt kredi, ak istwa prè yo.",
    usaReceiver: "Imel, telefòn, oswa $Cashtag",
    identityVerification: "Verifikasyon idantite",
    rejectIdentityAction: "Refize idantite",
    submitVerification: "Voye verifikasyon",
    verificationIntro: "Pran oswa telechaje pyès idantite, selfie, ak selfie ak pyès idantite. PRETEM ap itilize sa pou revize kont ou yon sèl fwa.",
    verificationNot_submitted: "Pa voye",
    verificationNotSubmitted: "Pa voye",
    verificationPending: "Ann atant",
    verificationPendingBody: "Verifikasyon ou an ann atant. Ou ka mande prè pandan admin nan ap revize dokiman yo.",
    verificationRejected: "Refize",
    verificationRejectedBody: "Verifikasyon an pa pase. Tanpri voye foto yo ankò ak enfòmasyon ki klè.",
    verificationStatus: "Estati verifikasyon",
    verificationSubmitError: "Nou pa kapab voye verifikasyon an.",
    verificationSubmitted: "Verifikasyon an voye. Admin nan ap revize li.",
    verificationVerified: "Verifye",
    verificationVerifiedBody: "Idantite ou verifye. Ou ka kontinye mande prè.",
    verification: "Verifikasyon",
    verifyBeforeLoan: "Tanpri verifye idantite ou anvan ou mande prè.",
    verifyIdentity: "Verifye idantite",
    verifyIdentityAction: "Verifye idantite"
  },
  en: {
    admin: "Admin",
    adminDashboard: "Admin dashboard",
    adminDashboardBody: "Choose a section to review documents, process new requests, or manage active loans.",
    adminLogin: "Admin login",
    adminReviewBody: "Admins can approve, reject, and track loan history.",
    adminReviewTitle: "Admin review",
    allStatuses: "All",
    adminAccessDenied: "This account does not have admin access.",
    actions: "Actions",
    acceptCreditReporting: "I understand that if I do not respect repayment terms, PRETEM may send the account to collections or report it to credit/consumer reporting agencies only as permitted by law.",
    acceptLawfulRecovery: "I understand that if I do not respect the loan terms, PRETEM may use lawful recovery methods, including private reminders, collections, legal action, or credit reporting as permitted by law.",
    acceptLoanTerms: "I agree to the terms, total payback amount, due date, and responsibility to provide accurate information.",
    acceptDocuments: "Accept documents",
    agreementRequired: "You must accept all required conditions before submitting.",
    approve: "Approve",
    approveLoan: "Approve loan",
    approveLoanNeedsDocs: "Accept the identity documents before approving the loan.",
    approvedShort: "Approved",
    authDescription: "PRETEM Credit helps the Haitian community request credit, verify identity, and track decisions with a clear reference number.",
    back: "Back",
    basicInfo: "Basic info",
    checkStatus: "Check status",
    checking: "Checking...",
    capturePhoto: "Take photo",
    cameraAccessError: "Could not open the camera. Please check camera permissions or upload a photo.",
    cameraPreview: "Camera preview",
    cancelRequest: "Cancel request",
    cancelRequestSuccess: "Request canceled.",
    closeCamera: "Close camera",
    continue: "Continue",
    contact: "Contact",
    countryHaiti: "Haiti",
    countryMexico: "Mexico",
    countryUsa: "USA",
    createAccount: "Create account",
    creditHistory: "Credit history",
    creditScore: "Credit score",
    currency: "Currency",
    dashboard: "Dashboard",
    dashboardVerificationApproved: "Good news: your identity verification was accepted. You can continue to request a loan.",
    dashboardVerificationNotSubmitted: "You have not submitted identity verification yet. Submit your documents so PRETEM can review your account.",
    dashboardVerificationPending: "Your identity verification is still pending. PRETEM is reviewing the documents.",
    dashboardVerificationRejected: "Your identity verification was not accepted. Please upload clear photos again.",
    dayUnit: "days",
    destinationCountry: "Which country do you need the money in?",
    destinationFallback: "Destination",
    documentReview: "Document review",
    documents: "Documents",
    dueDate: "Due date",
    dueIn: "Due in",
    download: "Download",
    downloadAgreement: "Download agreement",
    email: "Email",
    filterByStatus: "Filter by status",
    footerTrust: "Official PRETEM Credit platform for loan requests, identity verification, and status tracking.",
    fullName: "Full name",
    haitiMobileNumber: "MonCash/NatCash phone number",
    haitiAccountName: "Name on account",
    haitiPhoneHelp: "MonCash must be a Digicel number. NatCash must be a Natcom number.",
    haitiPhoneLengthError: "Use an 8-digit Haiti phone number, with or without +509.",
    hidePassword: "Hide password",
    openCamera: "Open camera",
    open: "Open",
    heroBody:
      "A practical micro-loan platform built for the Haitian community to request funds, complete identity verification, and track decisions with a clear reference number.",
    idPhoto: "ID photo",
    identityChecksBody: "Upload ID, selfie, and selfie with ID into Supabase Storage.",
    identityChecksTitle: "Identity checks",
    interest: "Interest",
    language: "Language",
    loadingAdminData: "Loading admin data...",
    loadingLoanHistory: "Loading loan history...",
    loadingTracker: "Loading tracker...",
    lastLoan: "Last loan",
    loanAmount: "Loan amount",
    loanDecision: "Loan decision",
    loanHistoryBody: "View your request history and repayment status.",
    loanInfo: "Loan info",
    loanManagement: "Loan management",
    loanRequests: "Loan requests",
    loanSummary: "Loan summary",
    loansShort: "loans",
    login: "Log in",
    loginTagline: "Easy and fast loan without history",
    menu: "Menu",
    markPaid: "Mark paid",
    methodBankTransfer: "Bank transfer",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Account name",
    mexicoBankName: "Bank name",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash requires a Digicel number.",
    myLoans: "My loans",
    natcashNatcomError: "NatCash requires a Natcom number.",
    noReceivingDetails: "No receiving details",
    moneySent: "Money sent",
    notProvided: "Not provided",
    password: "Password",
    paidShort: "Paid",
    pendingShort: "Pending",
    payoutInfo: "Receiving information",
    payoutMethod: "How do you want to receive the money?",
    phoneNumber: "Phone number",
    privacyPolicy: "Privacy Policy",
    printVerification: "Print verification",
    printWindowBlocked: "The browser blocked the print window. Please allow pop-ups for this site.",
    publicStoryConsent: "Optional: PRETEM may contact me for separate permission to share non-sensitive testimonials or marketing photos.",
    publicStoryConsentHelp: "PRETEM will not publish names, photos, ID documents, selfie with ID, debt information, or private verification documents on social media.",
    referenceNumber: "Reference number",
    reject: "Reject",
    rejectDocuments: "Reject documents",
    rejectLoan: "Reject loan",
    rejectedShort: "Rejected",
    repaymentPeriod: "Repayment period",
    repayment: "Repayment",
    repaymentProof: "Repayment proof",
    repaymentSubmitted: "Repayment proof submitted.",
    repaymentTransferId: "Repayment transfer ID",
    requested: "Requested",
    requiredAgreementHelp: "You must check the 3 required conditions before submitting.",
    rate: "rate",
    receiverLabel: "Receiver",
    reviewRequestsBody: "Review requests, inspect verification uploads, and manage repayment state.",
    requestLoan: "Request loan",
    requestSummary: "Request summary",
    requestStatusTitle: "Track a request",
    selfie: "Selfie",
    selfieWithId: "Selfie with ID",
    security: "Security",
    securityConfidentialityPolicy: "Security and confidentiality policy",
    searchUsers: "Search users",
    searchUsersPlaceholder: "Type name, email, phone, country, or reference",
    selectedFile: "Selected file",
    showPassword: "Show password",
    simpleRequestsBody: "Submit basic contact details, amount, and repayment preview.",
    simpleRequestsTitle: "Simple requests",
    signOut: "Sign out",
    sent: "Sent",
    signupCountry: "Country",
    statusApproved: "Approved",
    statusCanceled: "Canceled",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusRejected: "Rejected",
    status: "Status",
    submitLoanError: "Could not submit loan request.",
    submitRequest: "Submit request",
    submitting: "Submitting...",
    submitRepayment: "Submit payment proof",
    submitted: "Submitted",
    termsDisclosure: "Terms and loan disclosure",
    supabaseMissing: "Supabase is not configured yet. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to .env.local, then restart the dev server.",
    noLoansFound: "No loans found",
    noAdminItems: "There is nothing in this section right now.",
    noLoansFoundBody: "Once you request a loan, it will appear here.",
    noRequestFound: "No loan request was found for that reference.",
    newRequest: "New request",
    totalPayback: "Total payback",
    track: "Track",
    transferId: "Transfer ID",
    transferIdRequired: "Enter the transfer ID before continuing.",
    useLoginFirst: "You must be logged in.",
    users: "Users",
    usersDatabase: "Users database",
    usersDatabaseBody: "Everyone using the system, with account information, credit score, and loan history.",
    usaReceiver: "Email, phone, or $Cashtag",
    identityVerification: "Identity verification",
    rejectIdentityAction: "Reject identity",
    submitVerification: "Submit verification",
    verificationIntro: "Take or upload your ID, selfie, and selfie with ID. PRETEM will use this to review your account once.",
    verificationNot_submitted: "Not submitted",
    verificationNotSubmitted: "Not submitted",
    verificationPending: "Pending",
    verificationPendingBody: "Your verification is pending. You can request a loan while the admin reviews the documents.",
    verificationRejected: "Rejected",
    verificationRejectedBody: "The verification was not accepted. Please upload clear photos again.",
    verificationStatus: "Verification status",
    verificationSubmitError: "Could not submit verification.",
    verificationSubmitted: "Verification submitted. The admin will review it.",
    verificationVerified: "Verified",
    verificationVerifiedBody: "Your identity is verified. You can continue to request a loan.",
    verification: "Verification",
    verifyBeforeLoan: "Please verify your identity before requesting a loan.",
    verifyIdentity: "Verify identity",
    verifyIdentityAction: "Verify identity"
  },
  es: {
    admin: "Admin",
    adminDashboard: "Panel de admin",
    adminDashboardBody: "Elige una sección para revisar documentos, procesar nuevas solicitudes o administrar préstamos activos.",
    adminLogin: "Inicio de admin",
    adminReviewBody: "Los administradores pueden aprobar, rechazar y revisar el historial de préstamos.",
    adminReviewTitle: "Revisión admin",
    allStatuses: "Todos",
    adminAccessDenied: "Esta cuenta no tiene acceso de admin.",
    actions: "Acciones",
    acceptCreditReporting: "Entiendo que si no respeto los términos de pago, PRETEM puede enviar la cuenta a cobranza o reportarla a agencias de crédito/consumidor solo cuando la ley lo permita.",
    acceptLawfulRecovery: "Entiendo que si no respeto los términos del préstamo, PRETEM puede usar métodos legales de recuperación, como recordatorios privados, cobranza, acción legal o reporte de crédito cuando la ley lo permita.",
    acceptLoanTerms: "Acepto los términos, el total a pagar, la fecha límite y la responsabilidad de dar información correcta.",
    acceptDocuments: "Aceptar documentos",
    agreementRequired: "Debes aceptar todas las condiciones obligatorias antes de enviar.",
    approve: "Aprobar",
    approveLoan: "Aprobar préstamo",
    approveLoanNeedsDocs: "Acepta los documentos de identidad antes de aprobar el préstamo.",
    approvedShort: "Aprobados",
    authDescription: "PRETEM Credit ayuda a la comunidad haitiana a solicitar crédito, verificar identidad y seguir decisiones con un número de referencia claro.",
    back: "Atrás",
    basicInfo: "Información básica",
    checkStatus: "Ver estado",
    checking: "Verificando...",
    capturePhoto: "Tomar foto",
    cameraAccessError: "No se pudo abrir la cámara. Revisa los permisos de cámara o sube una foto.",
    cameraPreview: "Vista de cámara",
    cancelRequest: "Cancelar solicitud",
    cancelRequestSuccess: "Solicitud cancelada.",
    closeCamera: "Cerrar cámara",
    continue: "Continuar",
    contact: "Contacto",
    countryHaiti: "Haiti",
    countryMexico: "México",
    countryUsa: "EE. UU.",
    createAccount: "Crear cuenta",
    creditHistory: "Historial de crédito",
    creditScore: "Puntaje de crédito",
    currency: "Moneda",
    dashboard: "Panel",
    dashboardVerificationApproved: "Buenas noticias: tu verificación de identidad fue aceptada. Puedes continuar y solicitar un préstamo.",
    dashboardVerificationNotSubmitted: "Aún no has enviado la verificación de identidad. Envía tus documentos para que PRETEM revise tu cuenta.",
    dashboardVerificationPending: "Tu verificación de identidad sigue pendiente. PRETEM está revisando los documentos.",
    dashboardVerificationRejected: "Tu verificación de identidad no fue aceptada. Sube fotos claras otra vez.",
    dayUnit: "días",
    destinationCountry: "¿En qué país necesitas el dinero?",
    destinationFallback: "Destino",
    documentReview: "Revisión de documentos",
    documents: "Documentos",
    dueDate: "Fecha de pago",
    dueIn: "Vence en",
    download: "Descargar",
    downloadAgreement: "Descargar acuerdo",
    email: "Correo",
    filterByStatus: "Filtrar por estado",
    footerTrust: "Plataforma oficial de PRETEM Credit para solicitudes de préstamo, verificación de identidad y seguimiento de estado.",
    fullName: "Nombre completo",
    haitiMobileNumber: "Número MonCash/NatCash",
    haitiAccountName: "Nombre de la cuenta",
    haitiPhoneHelp: "MonCash debe ser Digicel. NatCash debe ser Natcom.",
    haitiPhoneLengthError: "Usa un número de Haiti de 8 dígitos, con o sin +509.",
    hidePassword: "Ocultar contraseña",
    openCamera: "Abrir cámara",
    open: "Abrir",
    heroBody:
      "Una plataforma práctica de micropréstamos para la comunidad haitiana que permite solicitar fondos, completar la verificación de identidad y seguir decisiones con un número de referencia claro.",
    idPhoto: "Foto de identificación",
    identityChecksBody: "Sube identificación, selfie y selfie con identificación a Supabase Storage.",
    identityChecksTitle: "Verificación de identidad",
    interest: "Interés",
    language: "Idioma",
    loadingAdminData: "Cargando datos de admin...",
    loadingLoanHistory: "Cargando historial de préstamos...",
    loadingTracker: "Cargando rastreador...",
    lastLoan: "Último préstamo",
    loanAmount: "Monto del préstamo",
    loanDecision: "Decisión del préstamo",
    loanHistoryBody: "Consulta tu historial de solicitudes y estado de pago.",
    loanInfo: "Información del préstamo",
    loanManagement: "Gestión de préstamos",
    loanRequests: "Solicitudes de préstamo",
    loanSummary: "Resumen de préstamos",
    loansShort: "préstamos",
    login: "Iniciar sesión",
    loginTagline: "Préstamo fácil y rápido sin historial",
    menu: "Menú",
    markPaid: "Marcar pagado",
    methodBankTransfer: "Transferencia bancaria",
    methodCashapp: "Cash App",
    methodMoncash: "MonCash",
    methodNatcash: "NatCash",
    methodZelle: "Zelle",
    mexicoAccountName: "Nombre de la cuenta",
    mexicoBankName: "Nombre del banco",
    mexicoClabe: "CLABE",
    moncashDigicelError: "MonCash requiere un número Digicel.",
    myLoans: "Mis préstamos",
    natcashNatcomError: "NatCash requiere un número Natcom.",
    noReceivingDetails: "No hay información para recibir",
    moneySent: "Dinero enviado",
    notProvided: "No proporcionado",
    password: "Contraseña",
    paidShort: "Pagados",
    pendingShort: "Pendientes",
    payoutInfo: "Información para recibir",
    payoutMethod: "¿Cómo quieres recibir el dinero?",
    phoneNumber: "Teléfono",
    privacyPolicy: "Política de privacidad",
    printVerification: "Imprimir verificación",
    printWindowBlocked: "El navegador bloqueó la ventana de impresión. Permite pop-ups para este sitio.",
    publicStoryConsent: "Opcional: PRETEM puede contactarme para pedir permiso separado para compartir testimonios o fotos de marketing no sensibles.",
    publicStoryConsentHelp: "PRETEM no publicará nombres, fotos, documentos de identificación, selfie con identificación, información de deuda ni documentos privados de verificación en redes sociales.",
    referenceNumber: "Número de referencia",
    reject: "Rechazar",
    rejectDocuments: "Rechazar documentos",
    rejectLoan: "Rechazar préstamo",
    rejectedShort: "Rechazados",
    repaymentPeriod: "Plazo de pago",
    repayment: "Pago",
    repaymentProof: "Prueba de pago",
    repaymentSubmitted: "Prueba de pago enviada.",
    repaymentTransferId: "ID de transferencia de pago",
    requested: "Solicitado",
    requiredAgreementHelp: "Debes marcar las 3 condiciones obligatorias antes de enviar.",
    rate: "tasa",
    receiverLabel: "Receptor",
    reviewRequestsBody: "Revisa solicitudes, verifica documentos y administra el estado de pago.",
    requestLoan: "Solicitar préstamo",
    requestSummary: "Resumen de solicitud",
    requestStatusTitle: "Rastrear solicitud",
    selfie: "Selfie",
    selfieWithId: "Selfie con identificación",
    security: "Seguridad",
    securityConfidentialityPolicy: "Política de seguridad y confidencialidad",
    searchUsers: "Buscar usuarios",
    searchUsersPlaceholder: "Escribe nombre, correo, teléfono, país o referencia",
    selectedFile: "Archivo seleccionado",
    showPassword: "Mostrar contraseña",
    simpleRequestsBody: "Envía datos de contacto, monto y vista previa del pago.",
    simpleRequestsTitle: "Solicitudes simples",
    signOut: "Cerrar sesión",
    sent: "Enviado",
    signupCountry: "País",
    statusApproved: "Aprobado",
    statusCanceled: "Cancelada",
    statusPaid: "Pagado",
    statusPending: "Pendiente",
    statusRejected: "Rechazado",
    status: "Estado",
    submitLoanError: "No se pudo enviar la solicitud.",
    submitRequest: "Enviar solicitud",
    submitting: "Enviando...",
    submitRepayment: "Enviar prueba de pago",
    submitted: "Enviado",
    termsDisclosure: "Términos e información del préstamo",
    supabaseMissing: "Supabase aún no está configurado. Agrega NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_ANON_KEY a .env.local, luego reinicia el servidor.",
    noLoansFound: "No hay préstamos",
    noAdminItems: "No hay nada en esta sección por ahora.",
    noLoansFoundBody: "Cuando solicites un préstamo, aparecerá aquí.",
    noRequestFound: "No se encontró una solicitud con esa referencia.",
    newRequest: "Nueva solicitud",
    totalPayback: "Total a pagar",
    track: "Rastrear",
    transferId: "ID de transferencia",
    transferIdRequired: "Ingresa el ID de transferencia antes de continuar.",
    useLoginFirst: "Debes iniciar sesión.",
    users: "Usuarios",
    usersDatabase: "Base de datos de usuarios",
    usersDatabaseBody: "Todas las personas que usan el sistema, con información de cuenta, puntaje de crédito e historial de préstamos.",
    usaReceiver: "Correo, teléfono o $Cashtag",
    identityVerification: "Verificación de identidad",
    rejectIdentityAction: "Rechazar identidad",
    submitVerification: "Enviar verificación",
    verificationIntro: "Toma o sube tu identificación, selfie y selfie con identificación. PRETEM usará esto para revisar tu cuenta una sola vez.",
    verificationNot_submitted: "No enviada",
    verificationNotSubmitted: "No enviada",
    verificationPending: "Pendiente",
    verificationPendingBody: "Tu verificación está pendiente. Puedes solicitar un préstamo mientras el admin revisa los documentos.",
    verificationRejected: "Rechazada",
    verificationRejectedBody: "La verificación no fue aceptada. Sube fotos claras otra vez.",
    verificationStatus: "Estado de verificación",
    verificationSubmitError: "No se pudo enviar la verificación.",
    verificationSubmitted: "Verificación enviada. El admin la revisará.",
    verificationVerified: "Verificada",
    verificationVerifiedBody: "Tu identidad está verificada. Puedes continuar y solicitar un préstamo.",
    verification: "Verificación",
    verifyBeforeLoan: "Verifica tu identidad antes de solicitar un préstamo.",
    verifyIdentity: "Verificar identidad",
    verifyIdentityAction: "Verificar identidad"
  }
};

const languageLabels: Record<Language, string> = {
  ht: "Kreyol",
  en: "English",
  es: "Español"
};

const LanguageContext = createContext<{
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}>({
  language: "ht",
  setLanguage: () => undefined,
  t: (key) => key
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ht");

  useEffect(() => {
    const saved = window.localStorage.getItem("pretem-language") as Language | null;
    if (saved && dictionaries[saved]) setLanguageState(saved);
  }, []);

  const value = useMemo(
    () => ({
      language,
      setLanguage: (nextLanguage: Language) => {
        setLanguageState(nextLanguage);
        window.localStorage.setItem("pretem-language", nextLanguage);
      },
      t: (key: string) => dictionaries[language][key] ?? key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageSelect() {
  const { language, setLanguage, t } = useLanguage();

  return (
    <label className="language-select">
      <span>{t("language")}</span>
      <select value={language} onChange={(event) => setLanguage(event.target.value as Language)}>
        {Object.entries(languageLabels).map(([value, label]) => (
          <option key={value} value={value}>
            {label}
          </option>
        ))}
      </select>
    </label>
  );
}
